In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [3]:
df = pd.read_csv("tripadvisor.csv")

In [4]:
df.head(3)

User country  Nr. reviews  Nr. hotel reviews  Helpful votes  Score  \
0          USA           11                  4             13      5   
1          USA          119                 21             75      3   
2          USA           36                  9             25      5   

  Period of stay Traveler type Swimming Pool Exercise Room Basketball Court  \
0        Dec-Feb       Friends            NO           YES               NO   
1        Dec-Feb      Business            NO           YES               NO   
2        Mar-May      Families            NO           YES               NO   

  Yoga Classes Club Free Wifi                              Hotel name  \
0           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
1           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
2           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   

  Hotel stars  Nr. rooms User continent  Member years Review month  \
0           3       3773  North America             9      January   
1           3       3773  North America             3      January   
2           3       3773  North America             2     February   

  Review weekday  
0       Thursday  
1         Friday  
2       Saturday

In [5]:
df.shape

(504, 20)

In [6]:
df.columns

Index(['User country', 'Nr. reviews', 'Nr. hotel reviews', 'Helpful votes',
       'Score', 'Period of stay', 'Traveler type', 'Swimming Pool',
       'Exercise Room', 'Basketball Court', 'Yoga Classes', 'Club',
       'Free Wifi', 'Hotel name', 'Hotel stars', 'Nr. rooms', 'User continent',
       'Member years', 'Review month', 'Review weekday'],
      dtype='object')

In [7]:
cat = list(df.select_dtypes(include=['object']).columns.values)
cat


['User country',
 'Period of stay',
 'Traveler type',
 'Swimming Pool',
 'Exercise Room',
 'Basketball Court',
 'Yoga Classes',
 'Club',
 'Free Wifi',
 'Hotel name',
 'Hotel stars',
 'User continent',
 'Review month',
 'Review weekday']

'Period of stay'

In [74]:
cat[1].index

<function str.index>

In [8]:
from sklearn import preprocessing
labenc = preprocessing.LabelEncoder()

['Dec-Feb' 'Mar-May' 'Jun-Aug' 'Sep-Nov']
df['Period of stay'] = df['Period of stay'].map({'Dec-Feb':'winter', 'Mar-May':'spring', 'Jun-Aug' :'summer','Sep-Nov':'autumn'})
for i in range(0, len(cat)):
    print(df[cat[i]].unique())

['USA' 'UK' 'Canada' 'India' 'Australia' 'New Zeland' 'Ireland' 'Egypt'
 'Finland' 'Kenya' 'Jordan' 'Netherlands' 'Syria' 'Scotland'
 'South Africa' 'Swiss' 'United Arab Emirates' 'Hungary' 'China' 'Greece'
 'Mexico' 'Croatia' 'Germany' 'Malaysia' 'Thailand' 'Phillippines'
 'Israel' 'India ' 'Belgium' 'Puerto Rico' 'Switzerland' 'Norway' 'France'
 'Spain' 'Singapore' 'Brazil' 'Costa Rica' 'Iran' 'Saudi Arabia'
 'Honduras' 'Denmark' 'Taiwan' 'Hawaii' 'Kuwait' 'Czech Republic' 'Japan'
 'Korea' 'Italy']
['winter' 'spring' 'summer' 'autumn']
['Friends' 'Business' 'Families' 'Solo' 'Couples']
['NO' 'YES']
['YES' 'NO']
['NO' 'YES']
['NO' 'YES']
['YES' 'NO']
['YES' 'NO']
['Circus Circus Hotel & Casino Las Vegas' 'Excalibur Hotel & Casino'
 'Monte Carlo Resort&Casino' 'Treasure Island- TI Hotel & Casino'
 'Tropicana Las Vegas - A Double Tree by Hilton Hotel' 'Caesars Palace'
 'The Cosmopolitan Las Vegas' 'The Palazzo Resort Hotel Casino'
 'Wynn Las Vegas' 'Trump International Hotel Las Vegas' 

Index(['User country', 'Nr. reviews', 'Nr. hotel reviews', 'Helpful votes',
       'Score', 'Period of stay', 'Traveler type', 'Swimming Pool',
       'Exercise Room', 'Basketball Court', 'Yoga Classes', 'Club',
       'Free Wifi', 'Hotel name', 'Hotel stars', 'Nr. rooms', 'User continent',
       'Member years', 'Review month', 'Review weekday'],
      dtype='object')

In [48]:
df[cat[1]].

RangeIndex(start=0, stop=504, step=1)

In [9]:
for i in range(0, len(cat)):
    df[cat[i]] = labenc.fit_transform(df[cat[i]])

In [10]:
df.head(5)

User country  Nr. reviews  Nr. hotel reviews  Helpful votes  Score  \
0            46           11                  4             13      5   
1            46          119                 21             75      3   
2            46           36                  9             25      5   
3            45           14                  7             14      4   
4             3            5                  5              2      4   

   Period of stay  Traveler type  Swimming Pool  Exercise Room  \
0               3              3              0              1   
1               3              0              0              1   
2               1              2              0              1   
3               1              3              0              1   
4               1              4              0              1   

   Basketball Court  Yoga Classes  Club  Free Wifi  Hotel name  Hotel stars  \
0                 0             0     1          1           2            0   
1                 0             0     1          1           2            0   
2                 0             0     1          1           2            0   
3                 0             0     1          1           2            0   
4                 0             0     1          1           2            0   

   Nr. rooms  User continent  Member years  Review month  Review weekday  
0       3773               3             9             4               4  
1       3773               3             3             4               0  
2       3773               3             2             3               2  
3       3773               2             6             3               0  
4       3773               3             7             7               5

In [11]:
np.asarray(df.columns.get_loc(cat[1]))

array(5)

In [12]:
arr=[]
for i in range(0,len(cat)):
    arr.append(df.columns.get_loc(cat[i]))
np.asarray(arr)

array([ 0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19])

In [13]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features = arr)
df = onehotencoder.fit_transform(df)

In [14]:
df1 = pd.DataFrame(df.toarray())

In [211]:
df1.head(5)

0    1    2    3    4    5    6    7    8    9   ...   116  117  118  119  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  1.0  0.0   

     120   121   122  123     124  125  
0   11.0   4.0  13.0  5.0  3773.0  9.0  
1  119.0  21.0  75.0  3.0  3773.0  3.0  
2   36.0   9.0  25.0  5.0  3773.0  2.0  
3   14.0   7.0  14.0  4.0  3773.0  6.0  
4    5.0   5.0   2.0  4.0  3773.0  7.0  

[5 rows x 126 columns]

In [15]:
X = df1.values[:,df1.columns!= 123]
y = df1.values[:,123]

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.30,random_state=2018)

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100,n_jobs=-1,random_state=50)

In [18]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [19]:
z = rf.predict(X_test)
z

array([4., 3., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 4., 5., 5., 4., 5.,
       5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 4., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 4., 4., 5., 5., 5., 4., 5., 5., 5., 5., 4.,
       4., 5., 5., 5., 4., 5., 5., 5., 4., 4., 5., 5., 4., 4., 4., 5., 5.,
       5., 4., 5., 4., 5., 5., 5., 4., 4., 4., 5., 5., 5., 4., 5., 4., 4.,
       5., 4., 5., 5., 4., 5., 3., 4., 5., 5., 4., 5., 5., 5., 5., 4., 5.,
       4., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 4., 4., 4., 5., 5., 5.,
       5., 5., 4., 5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 5., 5.,
       4., 4., 5., 5., 5., 5., 3., 4., 5., 5., 5., 5., 4., 4., 5., 4.])

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
     
    print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
     
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
     
    print("Report : ",
    classification_report(y_test, y_pred))

In [21]:
cal_accuracy(y_test,z)

Confusion Matrix:  [[ 0  0  0  1  1]
 [ 0  0  0  4  5]
 [ 0  0  1 10 11]
 [ 0  0  1 16 33]
 [ 0  0  1 13 55]]
Accuracy :  47.368421052631575
Report :               precision    recall  f1-score   support

        1.0       0.00      0.00      0.00         2
        2.0       0.00      0.00      0.00         9
        3.0       0.33      0.05      0.08        22
        4.0       0.36      0.32      0.34        50
        5.0       0.52      0.80      0.63        69

avg / total       0.41      0.47      0.41       152



C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
features = ['User country', 'Nr. reviews', 'Nr. hotel reviews', 'Helpful votes',
        'Period of stay', 'Traveler type', 'Swimming Pool',
       'Exercise Room', 'Basketball Court', 'Yoga Classes', 'Club',
       'Free Wifi', 'Hotel name', 'Hotel stars', 'Nr. rooms', 'User continent',
       'Member years', 'Review month', 'Review weekday']

In [23]:
list(zip(features,rf.feature_importances_))

[('User country', 0.0065414375535066795),
 ('Nr. reviews', 0.0012894925015896799),
 ('Nr. hotel reviews', 0.0015307945161179587),
 ('Helpful votes', 0.013487035969982065),
 ('Period of stay', 0.0),
 ('Traveler type', 0.0012670874236143331),
 ('Swimming Pool', 0.0),
 ('Exercise Room', 0.0),
 ('Basketball Court', 0.0005111498604034703),
 ('Yoga Classes', 0.002495932886339254),
 ('Club', 0.0015016759175359269),
 ('Free Wifi', 0.0),
 ('Hotel name', 0.0029293298922187265),
 ('Hotel stars', 0.0008958485089298754),
 ('Nr. rooms', 0.0007436807726837703),
 ('User continent', 0.0002318730084469827),
 ('Member years', 1.74960524221222e-05),
 ('Review month', 0.0025888815439242675),
 ('Review weekday', 0.0001715493794652318)]

In [24]:
df2 = pd.read_csv("tripadvisor.csv")

In [25]:
df2.head()

User country  Nr. reviews  Nr. hotel reviews  Helpful votes  Score  \
0          USA           11                  4             13      5   
1          USA          119                 21             75      3   
2          USA           36                  9             25      5   
3           UK           14                  7             14      4   
4       Canada            5                  5              2      4   

  Period of stay Traveler type Swimming Pool Exercise Room Basketball Court  \
0        Dec-Feb       Friends            NO           YES               NO   
1        Dec-Feb      Business            NO           YES               NO   
2        Mar-May      Families            NO           YES               NO   
3        Mar-May       Friends            NO           YES               NO   
4        Mar-May          Solo            NO           YES               NO   

  Yoga Classes Club Free Wifi                              Hotel name  \
0           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
1           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
2           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
3           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   
4           NO  YES       YES  Circus Circus Hotel & Casino Las Vegas   

  Hotel stars  Nr. rooms User continent  Member years Review month  \
0           3       3773  North America             9      January   
1           3       3773  North America             3      January   
2           3       3773  North America             2     February   
3           3       3773         Europe             6     February   
4           3       3773  North America             7        March   

  Review weekday  
0       Thursday  
1         Friday  
2       Saturday  
3         Friday  
4        Tuesday

In [26]:
df2=  df2.drop(columns=['Period of stay', 'Swimming Pool', 'Exercise Room','Free Wifi','Review weekday','Basketball Court','User continent'])

In [27]:
df2.shape

(504, 13)

In [28]:
df2.head(2)

User country  Nr. reviews  Nr. hotel reviews  Helpful votes  Score  \
0          USA           11                  4             13      5   
1          USA          119                 21             75      3   

  Traveler type Yoga Classes Club                              Hotel name  \
0       Friends           NO  YES  Circus Circus Hotel & Casino Las Vegas   
1      Business           NO  YES  Circus Circus Hotel & Casino Las Vegas   

  Hotel stars  Nr. rooms  Member years Review month  
0           3       3773             9      January  
1           3       3773             3      January

In [29]:
cat1 = list(df2.select_dtypes(include=['object']).columns.values)
cat1


['User country',
 'Traveler type',
 'Yoga Classes',
 'Club',
 'Hotel name',
 'Hotel stars',
 'Review month']

In [30]:
from sklearn import preprocessing
labenc1 = preprocessing.LabelEncoder()


for i in range(0, len(cat1)):
    print(df2[cat1[i]].unique())

['USA' 'UK' 'Canada' 'India' 'Australia' 'New Zeland' 'Ireland' 'Egypt'
 'Finland' 'Kenya' 'Jordan' 'Netherlands' 'Syria' 'Scotland'
 'South Africa' 'Swiss' 'United Arab Emirates' 'Hungary' 'China' 'Greece'
 'Mexico' 'Croatia' 'Germany' 'Malaysia' 'Thailand' 'Phillippines'
 'Israel' 'India ' 'Belgium' 'Puerto Rico' 'Switzerland' 'Norway' 'France'
 'Spain' 'Singapore' 'Brazil' 'Costa Rica' 'Iran' 'Saudi Arabia'
 'Honduras' 'Denmark' 'Taiwan' 'Hawaii' 'Kuwait' 'Czech Republic' 'Japan'
 'Korea' 'Italy']
['Friends' 'Business' 'Families' 'Solo' 'Couples']
['NO' 'YES']
['YES' 'NO']
['Circus Circus Hotel & Casino Las Vegas' 'Excalibur Hotel & Casino'
 'Monte Carlo Resort&Casino' 'Treasure Island- TI Hotel & Casino'
 'Tropicana Las Vegas - A Double Tree by Hilton Hotel' 'Caesars Palace'
 'The Cosmopolitan Las Vegas' 'The Palazzo Resort Hotel Casino'
 'Wynn Las Vegas' 'Trump International Hotel Las Vegas' 'The Cromwell'
 'Encore at wynn Las Vegas' 'Hilton Grand Vacations on the Boulevard'
 "Mar

In [31]:
for j in range(0, len(cat1)):
    df2[cat1[j]] = labenc1.fit_transform(df2[cat1[j]])

In [32]:
df2.head(2)

User country  Nr. reviews  Nr. hotel reviews  Helpful votes  Score  \
0            46           11                  4             13      5   
1            46          119                 21             75      3   

   Traveler type  Yoga Classes  Club  Hotel name  Hotel stars  Nr. rooms  \
0              3             0     1           2            0       3773   
1              0             0     1           2            0       3773   

   Member years  Review month  
0             9             4  
1             3             4

In [33]:
df2.columns.get_loc(cat1[1])

5

In [34]:
arr1=[]
for j in range(0,len(cat1)):
    arr1.append(df2.columns.get_loc(cat1[j]))
np.asarray(arr1)

array([ 0,  5,  6,  7,  8,  9, 12])

In [35]:
onehotencoder1=OneHotEncoder(categorical_features = arr1)
df2 = onehotencoder1.fit_transform(df2)

In [36]:
df3 = pd.DataFrame(df2.toarray())

In [37]:
df3.head(3)

0    1    2    3    4    5    6    7    8    9   ...   91   92   93   94   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   

     95    96    97   98      99   100  
0   11.0   4.0  13.0  5.0  3773.0  9.0  
1  119.0  21.0  75.0  3.0  3773.0  3.0  
2   36.0   9.0  25.0  5.0  3773.0  2.0  

[3 rows x 101 columns]

In [43]:
X1 = df3.values[:,df3.columns!= 98]
y1 = df3.values[:,98]

In [74]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X1)
X1 = scaler.transform(X1)

In [75]:
X1_train , X1_test , y1_train , y1_test = train_test_split(X1,y1,test_size=0.30,random_state=2018)

In [77]:
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(n_estimators= 90,n_jobs=-1,random_state=50)

In [57]:
rf1.fit(X1_train,y1_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=90, n_jobs=-1,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [58]:
z1 = rf1.predict(X1_test)
z1

array([3., 4., 5., 4., 5., 5., 5., 5., 4., 5., 5., 5., 4., 5., 5., 4., 5.,
       5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 4., 5., 5., 5., 4., 4., 5., 5., 5., 5., 5., 4., 5., 5., 4.,
       4., 5., 5., 5., 4., 5., 5., 5., 5., 4., 5., 5., 4., 4., 4., 4., 5.,
       5., 4., 5., 4., 5., 5., 5., 4., 4., 4., 5., 5., 4., 4., 5., 3., 4.,
       5., 5., 4., 5., 5., 5., 3., 4., 5., 4., 4., 5., 5., 5., 5., 4., 5.,
       4., 5., 5., 4., 4., 5., 5., 4., 5., 5., 5., 4., 4., 4., 4., 5., 5.,
       5., 5., 4., 5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 5., 5.,
       5., 4., 5., 4., 5., 4., 3., 4., 5., 5., 4., 5., 4., 4., 5., 4.])

In [59]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
     
    print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
     
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
     
    print("Report : ",
    classification_report(y_test, y_pred))

In [60]:
cal_accuracy(y1_test,z1)

Confusion Matrix:  [[ 0  0  0  1  1]
 [ 0  0  0  4  5]
 [ 0  0  1 10 11]
 [ 0  0  1 21 28]
 [ 0  0  2 14 53]]
Accuracy :  49.34210526315789
Report :               precision    recall  f1-score   support

        1.0       0.00      0.00      0.00         2
        2.0       0.00      0.00      0.00         9
        3.0       0.25      0.05      0.08        22
        4.0       0.42      0.42      0.42        50
        5.0       0.54      0.77      0.63        69

avg / total       0.42      0.49      0.44       152



C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [61]:
from sklearn.ensemble import GradientBoostingClassifier

In [123]:
clf = GradientBoostingClassifier(n_estimators=4, learning_rate=0.5, max_depth=1, random_state=0).fit(X1_train, y1_train)
   

In [124]:
clf_pred = clf.predict(X1_test)

In [125]:
cal_accuracy(y1_test,clf_pred)

Confusion Matrix:  [[ 0  0  0  1  1]
 [ 0  0  0  2  7]
 [ 0  0  1 12  9]
 [ 0  0  1 15 34]
 [ 1  0  1  5 62]]
Accuracy :  51.31578947368421
Report :               precision    recall  f1-score   support

        1.0       0.00      0.00      0.00         2
        2.0       0.00      0.00      0.00         9
        3.0       0.33      0.05      0.08        22
        4.0       0.43      0.30      0.35        50
        5.0       0.55      0.90      0.68        69

avg / total       0.44      0.51      0.44       152



C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
